import type { CSSProperties } from "react";

/** Co-located styles for AgentPerformanceView (extracted from inline styles). */
export const s = {
  page: { padding: "28px 32px 48px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 24 } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  summaryRow: { display: "flex", gap: 14, marginBottom: 24 } satisfies CSSProperties,
  donutsRow: { display: "flex", gap: 24, marginBottom: 30, flexWrap: "wrap" } satisfies CSSProperties,
  card: {
    flex: 1,
    minWidth: 320,
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  sortGroup: { display: "inline-flex", gap: 8, fontSize: 12 } satisfies CSSProperties,
  sortBtn: (active: boolean): CSSProperties => ({
    padding: "2px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    cursor: "pointer",
    textTransform: "capitalize",
  }),
  tableWrap: { border: "1px solid var(--border)", borderRadius: 9, overflow: "hidden" } satisfies CSSProperties,
  gridCols: "1.6fr 90px 80px 90px 90px 90px",
  headRow: {
    display: "grid",
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-surface)",
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  } satisfies CSSProperties,
  row: {
    display: "grid",
    gap: 12,
    padding: "12px 16px",
    borderTop: "1px solid var(--border)",
    alignItems: "center",
    fontSize: 13,
  } satisfies CSSProperties,
  agentName: { fontWeight: 600 } satisfies CSSProperties,
  agentMeta: { marginLeft: 10, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  mutedCell: { color: "var(--text-muted)" } satisfies CSSProperties,
  critCount: { color: "var(--crit)", marginLeft: 8 } satisfies CSSProperties,
} as const;
