import type React from "react";

export const s = {
  page: { padding: 28, maxWidth: 1040, margin: "0 auto" },
  header: { display: "flex", alignItems: "flex-start", gap: 20, marginBottom: 24 },
  headerText: { flex: 1, minWidth: 0 },
  h1: { fontSize: 24, lineHeight: 1.25, fontWeight: 750, margin: 0 },
  subtitle: { color: "var(--text-secondary)", fontSize: 14, lineHeight: 1.55, marginTop: 7 },
  actions: { display: "flex", gap: 10, flexShrink: 0 },
  summary: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: "var(--text-secondary)",
    fontSize: 13,
    marginBottom: 16,
  },
  list: { display: "flex", flexDirection: "column", gap: 14 },
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    padding: 18,
  },
  cardTop: { display: "flex", alignItems: "flex-start", gap: 16 },
  cardMain: { flex: 1, minWidth: 0 },
  category: {
    color: "var(--accent)",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".06em",
    marginBottom: 7,
  },
  rule: { fontSize: 15, fontWeight: 650, lineHeight: 1.45 },
  decision: { display: "flex", gap: 8, flexShrink: 0 },
  evidence: {
    marginTop: 14,
    border: "1px solid var(--border)",
    borderRadius: 7,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  },
  evidenceLink: {
    display: "block",
    padding: "8px 11px",
    borderBottom: "1px solid var(--border)",
    color: "var(--accent)",
    fontSize: 12,
    textDecoration: "none",
  },
  code: {
    padding: "10px 11px",
    margin: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    color: "var(--text-secondary)",
    fontSize: 12,
    lineHeight: 1.55,
  },
  meta: { display: "flex", alignItems: "center", gap: 10, marginTop: 12 },
  confidenceTrack: {
    width: 110,
    height: 4,
    borderRadius: 999,
    background: "var(--border)",
    overflow: "hidden",
  },
  editGrid: { display: "grid", gridTemplateColumns: "180px 1fr", gap: 10 },
  editActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 10 },
  modalBody: { padding: "20px 24px 4px" },
  modalFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16 },
  modalActions: { display: "flex", alignItems: "center", gap: 10 },
  saveDestination: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-muted)",
    fontSize: 12,
  },
  mergeBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "11px 13px",
    marginBottom: 18,
    border: "1px solid rgba(59, 130, 246, 0.18)",
    borderRadius: 7,
    background: "var(--accent-bg)",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    lineHeight: 1.5,
  },
  mergeBannerIcon: { flexShrink: 0, marginTop: 2, color: "var(--accent-text)" },
  mergeBannerStrong: { color: "var(--text-primary)", fontWeight: 700 },
  mergeBannerRepo: { color: "var(--accent-text)", fontWeight: 600 },
  settingsRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    gap: 18,
  },
  enabledControl: { display: "flex", alignItems: "center", gap: 10, minHeight: 42 },
  enabledHint: { color: "var(--text-muted)", fontSize: 11.5, lineHeight: 1.35 },
  editor: {
    overflow: "hidden",
    border: "1px solid var(--border-strong)",
    borderRadius: 8,
    background: "var(--code-bg)",
  },
  editorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 38,
    padding: "0 12px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 12,
  },
  editorFilename: { fontFamily: "var(--font-mono)", fontWeight: 600 },
  unsavedBadge: {
    padding: "2px 7px",
    borderRadius: 5,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    fontSize: 10.5,
  },
  tokenEstimate: { marginLeft: "auto", color: "var(--text-muted)" },
  editorContent: { display: "flex", height: 310, minHeight: 240 },
  lineNumbers: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    width: 46,
    overflow: "hidden",
    padding: "12px 10px",
    borderRight: "1px solid var(--border)",
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    lineHeight: 1.65,
    textAlign: "right",
    userSelect: "none",
  },
  editorTextarea: {
    flex: 1,
    width: "100%",
    height: "100%",
    resize: "none",
    overflow: "auto",
    padding: "12px 14px",
    border: 0,
    borderRadius: 0,
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: 1.65,
    tabSize: 2,
  },
} satisfies Record<string, React.CSSProperties>;
