import type { CSSProperties } from "react";

/** Co-located styles for MemoryView + its FilterGroup/CheckRow sub-components. */
export const s = {
  layout: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  filters: {
    width: 200,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    padding: 20,
    background: "var(--bg-surface)",
    overflow: "auto",
  } satisfies CSSProperties,
  listCol: { flex: 1, display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  listHeader: { padding: "18px 24px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 14, marginBottom: 14 } satisfies CSSProperties,
  h1: { fontSize: 20, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  searchForm: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "var(--text-primary)",
    background: "transparent",
    border: "none",
    outline: "none",
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    flex: 1,
    overflow: "auto",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  // FilterGroup
  group: { marginBottom: 24 } satisfies CSSProperties,
  groupLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 10,
  } satisfies CSSProperties,
  groupBody: { display: "flex", flexDirection: "column", gap: 5 } satisfies CSSProperties,
  // CheckRow
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
    padding: "2px 0",
    background: "none",
    border: "none",
    textAlign: "left",
    width: "100%",
  } satisfies CSSProperties,
  checkBox: (on: boolean): CSSProperties => ({
    width: 15,
    height: 15,
    borderRadius: 4,
    border: "1.5px solid " + (on ? "var(--accent)" : "var(--border-strong)"),
    background: on ? "var(--accent)" : "transparent",
    display: "inline-grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  checkIcon: { color: "#fff" } satisfies CSSProperties,
  checkLabel: { flex: 1, textTransform: "capitalize" } satisfies CSSProperties,
  checkCount: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
