import type { CSSProperties } from "react";

/** Co-located styles for ComposeReviewDrawer (extracted from inline styles). */
export const s = {
  footer: { display: "flex", alignItems: "center", gap: 10, width: "100%" } satisfies CSSProperties,
  inlineLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    marginRight: "auto",
  } satisfies CSSProperties,
  body: { padding: 18, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  postedBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid rgba(16,185,129,0.3)",
    background: "var(--ok-bg)",
  } satisfies CSSProperties,
  postedIcon: { color: "var(--ok)" } satisfies CSSProperties,
  postedText: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 8,
  } satisfies CSSProperties,
  verdictRow: { display: "flex", gap: 8 } satisfies CSSProperties,
  verdictBtn: (active: boolean, color: string): CSSProperties => ({
    flex: 1,
    padding: "10px 12px",
    borderRadius: 7,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    color: active ? "#fff" : color,
    background: active ? color : "var(--bg-elevated)",
    border: `1px solid ${active ? color : "var(--border)"}`,
  }),
  bodyHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 } satisfies CSSProperties,
  bodyLabel: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 320,
    resize: "vertical",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    lineHeight: 1.6,
    background: "var(--code-bg)",
    color: "var(--text-primary)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 14,
  } satisfies CSSProperties,
} as const;
