import type { CommunityCatalogEntry } from './contracts.js';

/**
 * Static, curated community-skill catalog (Phase 9). This is a course-project
 * fixture, NOT a live index — there is no crawler and no external API call.
 * Search/filter (`GET /skills/community`) runs entirely in-memory over this
 * array; import (`POST /skills/community/:slug/import`) needs no network
 * call since each entry already carries its full body.
 */
export const COMMUNITY_CATALOG: CommunityCatalogEntry[] = [
  {
    slug: 'owasp-top-10-review',
    name: 'owasp-top-10-review',
    repo: 'secdev/agent-skills',
    stars: 1240,
    lang: 'any',
    desc: 'Maps diff changes to the OWASP Top 10 with CWE references.',
    topics: ['security'],
    type: 'security',
    body: '# OWASP Top 10 Review\n\nFor each changed file, check whether the diff introduces or touches code matching an OWASP Top 10 category (injection, broken access control, cryptographic failures, etc.). When it does, cite the specific category and CWE id in the finding rationale.',
  },
  {
    slug: 'react-hooks-rules',
    name: 'react-hooks-rules',
    repo: 'frontend-guild/skills',
    stars: 842,
    lang: 'TypeScript',
    desc: 'Detects conditional hooks, missing deps, stale closures.',
    topics: ['correctness'],
    type: 'convention',
    body: '# React Hooks Rules\n\nFlag hooks called conditionally or inside loops, `useEffect`/`useMemo`/`useCallback` dependency arrays missing a referenced value, and closures capturing stale state across renders.',
  },
  {
    slug: 'sql-injection-gate',
    name: 'sql-injection-gate',
    repo: 'secdev/agent-skills',
    stars: 690,
    lang: 'any',
    desc: 'Flags string-concatenated SQL and unparameterized queries.',
    topics: ['security'],
    type: 'security',
    body: '# SQL Injection Gate\n\nFlag any SQL string built via concatenation or template interpolation of untrusted input. Require parameterized queries or a query builder; cite the exact line where user input reaches the query string.',
  },
  {
    slug: 'a11y-jsx-audit',
    name: 'a11y-jsx-audit',
    repo: 'a11y-collective/skills',
    stars: 318,
    lang: 'TypeScript',
    desc: 'Checks JSX for missing alt text, ARIA, and focus traps.',
    topics: ['accessibility'],
    type: 'convention',
    body: '# Accessibility JSX Audit\n\nFlag `<img>` without `alt`, interactive elements without an accessible name, and modal/dialog components that do not trap or restore focus.',
  },
  {
    slug: 'n-plus-one-detector',
    name: 'n-plus-one-detector',
    repo: 'perfteam/skills',
    stars: 512,
    lang: 'any',
    desc: 'Flags loops issuing one DB query per iteration.',
    topics: ['performance'],
    type: 'rubric',
    body: '# N+1 Query Detector\n\nFlag a loop (for/forEach/map) whose body calls a query/fetch function once per iteration where a single batched query would suffice. Suggest the batched form.',
  },
  {
    slug: 'secrets-scanner',
    name: 'secrets-scanner',
    repo: 'secdev/agent-skills',
    stars: 975,
    lang: 'any',
    desc: 'Detects hardcoded API keys, tokens, and credentials in diffs.',
    topics: ['security'],
    type: 'security',
    body: '# Secrets Scanner\n\nFlag any literal-looking API key, access token, private key, or password assigned to a variable/constant in the diff. Common patterns: `sk_live_`, `AKIA`, `-----BEGIN PRIVATE KEY-----`, long base64/hex blobs assigned to `*_KEY`/`*_SECRET`/`*_TOKEN`.',
  },
  {
    slug: 'commit-message-lint',
    name: 'commit-message-lint',
    repo: 'devtools/skills',
    stars: 204,
    lang: 'any',
    desc: 'Flags vague or missing context in the PR description.',
    topics: ['style'],
    type: 'convention',
    body: '# PR Description Quality\n\nIf the PR description does not explain WHY the change was made (not just what), flag it as a suggestion. One-line "fix bug" descriptions on non-trivial diffs should prompt for more context.',
  },
  {
    slug: 'python-type-hints',
    name: 'python-type-hints',
    repo: 'pytypes/skills',
    stars: 431,
    lang: 'Python',
    desc: 'Flags missing type hints on new public functions.',
    topics: ['correctness'],
    type: 'convention',
    body: '# Python Type Hints\n\nFlag new public (non-underscore-prefixed) functions/methods added in the diff that have no parameter or return type annotations.',
  },
  {
    slug: 'go-error-wrapping',
    name: 'go-error-wrapping',
    repo: 'gophers/skills',
    stars: 356,
    lang: 'Go',
    desc: 'Checks errors are wrapped with context via fmt.Errorf %w.',
    topics: ['correctness'],
    type: 'convention',
    body: '# Go Error Wrapping\n\nFlag `return err` (bare, unwrapped) where the surrounding function has enough context to add a `fmt.Errorf("doing X: %w", err)` wrapper. Bare returns at the outermost boundary (main, handler) are fine.',
  },
  {
    slug: 'rate-limit-guard',
    name: 'rate-limit-guard',
    repo: 'secdev/agent-skills',
    stars: 288,
    lang: 'any',
    desc: 'Flags new endpoints without rate limiting.',
    topics: ['security'],
    type: 'security',
    body: '# Rate Limit Guard\n\nFlag a new HTTP route/endpoint added in the diff that has no rate-limiting middleware/decorator applied, especially auth, search, or write endpoints.',
  },
  {
    slug: 'test-flakiness-heuristics',
    name: 'test-flakiness-heuristics',
    repo: 'qa-guild/skills',
    stars: 267,
    lang: 'any',
    desc: 'Flags time-based sleeps and non-deterministic test ordering.',
    topics: ['testing'],
    type: 'rubric',
    body: '# Test Flakiness Heuristics\n\nFlag tests using a fixed `sleep`/`setTimeout` to wait for async work instead of polling/awaiting a real condition, and tests whose assertions depend on Set/Map/object key iteration order.',
  },
  {
    slug: 'css-specificity-audit',
    name: 'css-specificity-audit',
    repo: 'frontend-guild/skills',
    stars: 189,
    lang: 'TypeScript',
    desc: 'Flags !important and deeply nested selectors.',
    topics: ['style'],
    type: 'convention',
    body: '# CSS Specificity Audit\n\nFlag new `!important` declarations and selectors nested more than 3 levels deep — both are signals of a specificity fight that will be hard to override later.',
  },
];
