import type { CSSProperties } from "react";

/** Co-located styles for the Export-to-CI wizard (extracted from inline styles). */
export const s = {
  footer: { display: "flex", alignItems: "center", width: "100%" } satisfies CSSProperties,
  footerRight: { marginLeft: "auto" } satisfies CSSProperties,
  stepsBar: { padding: "20px 24px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  body: { padding: 24 } satisfies CSSProperties,
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 14,
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  targetGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 } satisfies CSSProperties,
  targetCard: (active: boolean): CSSProperties => ({
    textAlign: "left",
    padding: 18,
    borderRadius: 10,
    cursor: "pointer",
    background: "var(--bg-surface)",
    border: `1.5px solid ${active ? "var(--accent)" : "var(--border)"}`,
  }),
  targetHead: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  targetIconWrap: (active: boolean): CSSProperties => ({
    width: 34,
    height: 34,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    display: "grid",
    placeItems: "center",
    color: active ? "var(--accent)" : "var(--text-secondary)",
  }),
  targetName: { fontSize: 15, fontWeight: 600 } satisfies CSSProperties,
  targetBadge: { marginLeft: "auto" } satisfies CSSProperties,
  targetDesc: { fontSize: 13, color: "var(--text-muted)", marginTop: 10 } satisfies CSSProperties,
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
  } satisfies CSSProperties,
  fileList: {
    borderRight: "1px solid var(--border)",
    padding: 12,
    background: "var(--bg-surface)",
    overflow: "auto",
  } satisfies CSSProperties,
  fileListLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.05em",
    padding: "2px 10px 10px",
  } satisfies CSSProperties,
  fileRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 13,
    background: active ? "var(--accent-bg)" : "transparent",
  }),
  fileIcon: (active: boolean): CSSProperties => ({
    color: active ? "var(--accent)" : "var(--text-muted)",
    flexShrink: 0,
  }),
  fileName: (active: boolean): CSSProperties => ({ color: active ? "var(--accent-text)" : "var(--text-secondary)" }),
  generating: { fontSize: 13, color: "var(--text-muted)", padding: 10 } satisfies CSSProperties,
  fileViewer: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  fileViewerHead: {
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  fileViewerPath: { fontSize: 13, flex: 1 } satisfies CSSProperties,
  fileViewerPre: {
    margin: 0,
    padding: 16,
    fontSize: 12,
    lineHeight: 1.6,
    overflow: "auto",
    flex: 1,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  configWrap: { maxWidth: 600 } satisfies CSSProperties,
  triggerChips: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  postAsList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  postAsLabel: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 14,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  radio: (active: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 99,
    border: `1.5px solid ${active ? "var(--accent)" : "var(--border-strong)"}`,
    display: "grid",
    placeItems: "center",
  }),
  radioDot: { width: 8, height: 8, borderRadius: 99, background: "var(--accent)" } satisfies CSSProperties,
  blockMerge: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    opacity: 0.7,
  } satisfies CSSProperties,
  blockMergeTitle: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  blockMergeDesc: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  installWrap: { maxWidth: 600 } satisfies CSSProperties,
  installCard: {
    width: "100%",
    textAlign: "left",
    padding: 20,
    borderRadius: 10,
    border: "1.5px solid var(--accent)",
    background: "var(--accent-bg)",
    marginBottom: 14,
  } satisfies CSSProperties,
  installCardHead: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 } satisfies CSSProperties,
  installCardIcon: { color: "var(--accent)" } satisfies CSSProperties,
  installCardTitle: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  installCardBadge: { marginLeft: "auto" } satisfies CSSProperties,
  installCardBody: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  secretNote: { fontSize: 12, color: "var(--text-muted)", textAlign: "center" } satisfies CSSProperties,
} as const;
