import type { CSSProperties } from "react";

/** Co-located styles for the CI Runs view (extracted from inline styles). */
export const s = {
  emptyWrap: { padding: "24px 32px" } satisfies CSSProperties,
  header: { padding: "24px 32px 8px", display: "flex", alignItems: "flex-end", gap: 14 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  headerActions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  autoRefresh: {
    fontSize: 12,
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  autoDot: { width: 6, height: 6, borderRadius: 99, background: "var(--ok)" } satisfies CSSProperties,
  chips: { display: "flex", gap: 10, padding: "14px 32px", flexWrap: "wrap" } satisfies CSSProperties,
  tableWrap: {
    margin: "8px 32px 44px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headRow: (cols: string): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: cols,
    gap: 14,
    padding: "12px 18px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  }),
  row: (cols: string, last: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: cols,
    gap: 14,
    padding: "14px 18px",
    borderBottom: last ? "none" : "1px solid var(--border)",
    alignItems: "center",
    fontSize: 13,
  }),
  ranAt: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  prCell: { minWidth: 0 } satisfies CSSProperties,
  prNumber: { fontSize: 12, color: "var(--accent-text)" } satisfies CSSProperties,
  agent: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  findings: { fontSize: 13 } satisfies CSSProperties,
  cost: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  viewLink: { fontSize: 13, color: "var(--accent-text)" } satisfies CSSProperties,
  viewIcon: { verticalAlign: "middle" } satisfies CSSProperties,
  dash: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
