import type { CSSProperties } from "react";

export const s = {
  container: { display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,
  tokenStatus: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--text-muted)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  splitBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    color: "var(--warn)",
    fontSize: 13,
    fontWeight: 600,
  } satisfies CSSProperties,
  group: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  groupHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "4px 0",
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  groupChevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(90deg)" : "none",
    transition: "transform .12s",
    flexShrink: 0,
  }),
  groupIcon: { color: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  groupCopy: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    flex: 1,
  } satisfies CSSProperties,
  groupTitle: { fontSize: 13, fontWeight: 700, whiteSpace: "nowrap" } satisfies CSSProperties,
  groupDescription: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  groupCount: {
    marginLeft: "auto",
    color: "var(--text-muted)",
    fontSize: 12.5,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  groupFiles: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
} as const;
