import type { CSSProperties } from "react";

/** Co-located styles for ContextDocPicker (single-consumer tree — see
 *  `client/INSIGHTS.md` 2026-08-04 colocation rule). */
export const s = {
  wrap: { width: "100%", display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,
  summaryBar: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  summaryTotal: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  mapReduceNote: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "4px 0 8px",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowUnresolved: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  handle: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 18,
    flexShrink: 0,
    padding: 0,
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    cursor: "grab",
  } satisfies CSSProperties,
  handleSpacer: { width: 18, flexShrink: 0 } satisfies CSSProperties,
  path: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  nameCol: { flex: 1, minWidth: 0, display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  fileName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  folder: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  /** Fixed-width columns so the source badge and token count line up across
   *  rows instead of each shifting with its own label/number length. */
  sourceBadge: { width: 62, flexShrink: 0, justifyContent: "center" } satisfies CSSProperties,
  tokenBadge: { width: 78, flexShrink: 0, justifyContent: "flex-end" } satisfies CSSProperties,
  emptyNote: { fontSize: 13, color: "var(--text-muted)", padding: "8px 2px" } satisfies CSSProperties,
  loadError: { fontSize: 13, color: "var(--crit)", padding: "8px 2px" } satisfies CSSProperties,
  previewBody: { display: "flex", flexDirection: "column", gap: 12, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  previewRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  previewPath: { fontSize: 13, color: "var(--text-primary)", wordBreak: "break-all" } satisfies CSSProperties,
  previewMeta: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  previewContent: { paddingTop: 4 } satisfies CSSProperties,
  previewError: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
} as const;
