import type { CSSProperties } from "react";

/** Co-located styles for MultiAgentView (extracted from inline styles). */
export const s = {
  // ---- FindingMini ----
  findingCard: (color: string): CSSProperties => ({
    padding: "10px 12px",
    borderRadius: 6,
    background: "var(--bg-surface)",
    borderLeft: `2px solid ${color}`,
  }),
  findingHead: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  findingIcon: (color: string): CSSProperties => ({ color, flexShrink: 0 }),
  findingTitle: { fontSize: 13, fontWeight: 600, lineHeight: 1.3 } satisfies CSSProperties,
  findingMeta: { fontSize: 12, color: "var(--text-muted)", marginTop: 5 } satisfies CSSProperties,
  trifectaBadge: { marginLeft: 8 } satisfies CSSProperties,

  // ---- ColHeader ----
  colHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  colHeaderIcon: (color: string): CSSProperties => ({
    width: 30,
    height: 30,
    borderRadius: 8,
    display: "grid",
    placeItems: "center",
    background: `${color}1f`,
    color,
    flexShrink: 0,
  }),
  colHeaderBody: { minWidth: 0, flex: 1 } satisfies CSSProperties,
  colHeaderName: {
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  colHeaderMeta: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- ConflictsSection ----
  conflictsWrap: { marginTop: 24 } satisfies CSSProperties,
  conflictToggleLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  conflictsEmpty: { fontSize: 13, color: "var(--text-muted)", padding: "10px 2px" } satisfies CSSProperties,
  conflictsList: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  conflictCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  conflictCardHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  conflictIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  conflictLoc: { fontSize: 13 } satisfies CSSProperties,
  conflictTitle: { fontSize: 14, fontWeight: 600, marginLeft: 8 } satisfies CSSProperties,
  conflictTakesGrid: (n: number): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: `repeat(${n}, 1fr)`,
    gap: 1,
    background: "var(--border)",
  }),
  conflictTake: { padding: "12px 16px", background: "var(--bg-elevated)" } satisfies CSSProperties,
  takePersona: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
  } satisfies CSSProperties,
  takeVerdictRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 5 } satisfies CSSProperties,
  takeDot: (color: string): CSSProperties => ({ width: 7, height: 7, borderRadius: 99, background: color }),
  takeVerdict: (flagged: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color: flagged ? "var(--text-primary)" : "var(--text-muted)",
    textTransform: flagged ? "uppercase" : "none",
    letterSpacing: flagged ? "0.03em" : 0,
  }),
  takeNote: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,

  // ---- ColumnsView ----
  columnsPad: { padding: "24px 32px 44px" } satisfies CSSProperties,
  columnsGrid: (cols: number, scroll: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: `repeat(${cols}, minmax(220px, 1fr))`,
    gap: 14,
    overflowX: scroll ? "auto" : "visible",
  }),
  column: (color: string): CSSProperties => ({
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  }),
  columnHeadCell: (color: string): CSSProperties => ({
    padding: 14,
    borderBottom: "1px solid var(--border)",
    borderTop: `2px solid ${color}`,
  }),
  columnBody: { padding: 14, display: "flex", flexDirection: "column", gap: 8, flex: 1 } satisfies CSSProperties,
  columnEmpty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  columnFoot: {
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  linkBtn: { background: "transparent", border: "none", padding: 0, cursor: "pointer" } satisfies CSSProperties,
  columnFootCount: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- TabsView ----
  tabsPad: { padding: "0 0 44px" } satisfies CSSProperties,
  tabBar: {
    display: "flex",
    gap: 2,
    padding: "0 32px",
    borderBottom: "1px solid var(--border)",
    overflowX: "auto",
  } satisfies CSSProperties,
  tab: (on: boolean, color: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 18px",
    border: "none",
    background: "transparent",
    borderBottom: `2px solid ${on ? color : "transparent"}`,
    marginBottom: -1,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  tabIcon: (on: boolean, color: string): CSSProperties => ({ color: on ? color : "var(--text-muted)" }),
  tabName: (on: boolean): CSSProperties => ({
    fontSize: 14,
    fontWeight: on ? 600 : 500,
    color: on ? "var(--text-primary)" : "var(--text-secondary)",
  }),
  tabScore: (color: string): CSSProperties => ({ fontSize: 12, fontWeight: 700, color }),
  tabPanel: { padding: "24px 32px", maxWidth: 760 } satisfies CSSProperties,
  tabSummaryCard: (color: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "16px 18px",
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 20,
    borderLeft: `3px solid ${color}`,
  }),
  tabSummaryName: (color: string): CSSProperties => ({ fontSize: 15, fontWeight: 600, color }),
  tabSummaryText: {
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 5,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  tabSummaryAside: {
    marginLeft: "auto",
    textAlign: "right",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  } satisfies CSSProperties,
  tabSummaryMeta: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  tabFindings: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  tabConflictsPad: { padding: "0 32px" } satisfies CSSProperties,
} as const;
